# Generated by Django 4.2.8 on 2023-12-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Аватар', null=True, upload_to='account_images/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='article_images/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Баннер'),
        ),
    ]
