# Generated by Django 4.2.7 on 2023-11-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comments_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='banner (Баннер)'),
        ),
    ]
