# Generated by Django 4.2.8 on 2023-12-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tag_options_favoritearticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
