# Generated by Django 4.2.7 on 2023-11-28 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_account_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at (Дата создания)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)ss_created', to=settings.AUTH_USER_MODEL, verbose_name='created_by (Кто создал)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='created_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='created_name (Кто создал)'),
        ),
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at (Дата создания)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='created_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='created_name (Кто создал)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(verbose_name='created_at (Дата создания)'),
        ),
    ]
