# Generated by Django 4.2.7 on 2023-11-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_article_created_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleViews',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.article')),
                ('count_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
