# Generated by Django 4.2.7 on 2023-11-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_articleviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'pub_date'], 'verbose_name': 'Article (Новость)', 'verbose_name_plural': 'Articles (Новости)'},
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
    ]
