# Generated by Django 4.2.7 on 2023-11-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_tag_options_rename_name_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, help_text='Название категории', max_length=20, unique=True, verbose_name='title (Категория)'),
        ),
    ]
