# Generated by Django 4.2.7 on 2023-11-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_account_account_image_alter_account_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_image',
            new_name='avatar',
        ),
    ]
