# Generated by Django 4.2.7 on 2023-12-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Заголовок статьи', max_length=200, verbose_name='title (Заголовок)'),
        ),
    ]
