# Generated by Django 4.2.7 on 2023-12-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_article_options_remove_article_pub_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='news',
            new_name='article',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='pub_date',
        ),
    ]
