# Generated by Django 4.2.7 on 2023-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_news_comments_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='annotation',
            field=models.TextField(default='', help_text='Аннотация статьи', verbose_name='annotation (Аннотация)'),
            preserve_default=False,
        ),
    ]
