# Generated by Django 4.2.8 on 2023-12-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_article_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleViews',
        ),
    ]
