# Generated by Django 4.2.8 on 2023-12-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_comment_delete_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('title', 'status'), 'verbose_name': 'Tag (Тэг)', 'verbose_name_plural': 'Tags (Тэги)'},
        ),
    ]
