# Generated by Django 4.2.8 on 2023-12-11 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0032_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('title', 'status'), 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='views',
            options={'verbose_name': 'Количество просмотров', 'verbose_name_plural': 'Количество просмотров'},
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Аватар', null=True, upload_to='account_images', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(blank=True, help_text='День рождения', null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('U', 'Не выбрано')], default='U', help_text='Пол', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(help_text='Nickname', max_length=20, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='annotation',
            field=models.TextField(help_text='Аннотация статьи', verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Содержание статьи', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)ss_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Заголовок статьи', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, help_text='Название категории', max_length=20, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)ss_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.BooleanField(default=True, help_text='Статус тэга', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(help_text='Название тэга', max_length=80, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='views',
            name='count',
            field=models.PositiveIntegerField(default=0, help_text='Количество просмотров новости', verbose_name='Количество просмотров'),
        ),
    ]
