# Generated by Django 4.2.8 on 2023-12-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_account_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(help_text='Комментарий к новости', verbose_name='Комментарий'),
        ),
    ]
