# Generated by Django 4.2.7 on 2023-11-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_article_title_alter_comments_news_delete_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_name',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='created_name',
        ),
    ]
