# Generated by Django 4.2.7 on 2023-11-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_categories_category_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='birthdate',
            new_name='birthday',
        ),
    ]
