# Generated by Django 4.2.7 on 2023-11-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_birthdate_account_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Содержание новости', verbose_name='content (Содержание)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(help_text='Дата публикации', verbose_name='pub_date (Дата публикации)'),
        ),
    ]
