# Generated by Django 4.2.7 on 2023-11-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_article_content_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title', 'status'], 'verbose_name': 'Tag (Тэг)', 'verbose_name_plural': 'Tags (Тэги)'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
