# Generated by Django 4.2.7 on 2023-11-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleviews',
            options={'verbose_name': 'ArticleViews (Количество просмотров)', 'verbose_name_plural': 'ArticleViews (Количество просмотров)'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AlterField(
            model_name='articleviews',
            name='count_views',
            field=models.PositiveIntegerField(default=0, help_text='Количество просмотров новости', verbose_name='count_views (Количество просмотров)'),
        ),
    ]
