# Generated by Django 4.2.7 on 2023-11-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_articleviews_options_remove_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('U', 'Не выбрано')], max_length=1),
        ),
    ]
