# Generated by Django 4.2.7 on 2023-12-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'created_at'], 'verbose_name': 'Article (Статья)', 'verbose_name_plural': 'Articles (Статьи)'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Содержание статьи', verbose_name='content (Содержание)'),
        ),
    ]
