# Generated by Django 4.2.8 on 2023-12-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_article_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, help_text='Количество просмотров новости', verbose_name='count (Количество просмотров)')),
            ],
            options={
                'verbose_name': 'Views (Количество просмотров)',
                'verbose_name_plural': 'Views (Количество просмотров)',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.views'),
            preserve_default=False,
        ),
    ]
