# Generated by Django 4.2.8 on 2023-12-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.views'),
            preserve_default=False,
        ),
    ]
