# Generated by Django 4.2.8 on 2023-12-10 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0030_delete_articleviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at (Дата создания)')),
                ('message', models.TextField(help_text='Комментарий к новости', verbose_name='message (Комментарий)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)ss_created', to=settings.AUTH_USER_MODEL, verbose_name='created_by (Кто создал)')),
            ],
            options={
                'verbose_name': 'Comment (Комментарий)',
                'verbose_name_plural': 'Comment (Комментарий)',
            },
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
